name: 'Gitbook-Action'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v1

    - name: Gitbook Action
      uses: liyi4x/gitbook-pub@tv3
      with:
        token: ${{ secrets.TOKEN }}
        time_zone: Asia/Shanghai   # set time zone
